### ISSUE TITLE
Passing parameters/environment variables to docker-compose

### ISSUE THREAD

**Issue by jmbsoftwaresolutions** [troykinsella/concourse-docker-compose-resource#1]
I am trying to set up a Concourse pipeline that uses this resource type to deply to my dev/test environment after a successful build.  However, my docker-compose file has some environment variables declared to pass into the containers when started, and i'm not seeing how that's done with either this resource type or concourse in general.  From what I can tell from the documentation, the resource type has to explicitly declare the environment variables it will accept from the pipeline.  Is this a feature that would need to be added or is there something i'm missing?

**Comment by troykinsella** [comment]
This resource doesn't attempt to pass in any environment variables to the docker-compose execution, so that is definitely a welcome feature addition.

**Comment by troykinsella** [comment]
Attempting to address this with PR #2

**Comment by jmbsoftwaresolutions** [comment]
Works like a charm.  Thanks!
